### ISSUE TITLE
Button start slot without content shows margin

### ISSUE THREAD

**Issue by supun-io** [hyvor/design#108]
Svelte doesn't support conditional slots. So, in apps we cannot do this:

```svelte
<Button>
    {#if loading}<Loader slot="start" />{/if}
</Button>
```

The only solution is to wrap the loader:

```svelte
<Button>
     <span slot="start">{#if loading}<Loader  />{/if}</span>
</Button>
```

But, when the loader is not there, the `<Button>` element shows a margin (because the slot is set, even its empty)

![image](https://github.com/hyvor/design/assets/44988673/b60f8370-beac-4e6c-98df-d06fc8521644)

Maybe check CSS `:empty`?

**Comment by supun-io** [comment]
Update: solution:

- [ ] Add `:empty()` check to the design system (only add margin if the content is not empty in the start/end slots)
- [ ] In apps, we have to use `<svelte:fragment>` instead of span

**Comment by IshiniAvindya** [comment]
adding `:empty()` does not solve anything.
@supun-io
